--- #YAML:1.0
name:               Tie-DBI
version:            1.04
abstract:           Tie hashes to DBI relational databases
author:
    - Lincoln D. Stein <lds@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    DBD::SQLite:          0
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    DBI:         0
    Test::More:  0
resources:
    homepage:    http://wiki.github.com/toddr/Tie-DBI/
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/toddr/Tie-DBI
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
